backend:
  name: github
  repo: jameswrightdev/joy_starter_kit
  branch: feature/mark_down

media_folder: static/assets
public_folder: assets

collections:
  - name: "content"
    label: "content"
    files:
      - file: "src/content/about/index.md"
        label: "About"
        name: "index"
        fields: [{label: "name", name: "Your Name", widget: "string" }]